// Generates platform code from shared/*.json.
//   node scripts/gen-shared.mjs          write generated files
//   node scripts/gen-shared.mjs --check  exit 1 if any generated file is stale (used by `npm test`)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = (p) => JSON.parse(readFileSync(root + p, 'utf8'));
const tokens = read('shared/design-tokens.json');

const HEADER = 'GENERATED by scripts/gen-shared.mjs from shared/design-tokens.json. Do not edit by hand.';

// ---------- helpers ----------

const flatten = (node, prefix = []) =>
  Object.entries(node).flatMap(([key, value]) =>
    typeof value === 'object' ? flatten(value, [...prefix, key]) : [[[...prefix, key], value]],
  );

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');

const cssVar = (path) => `--fp-${path.map(kebab).join('-')}`;

/** Tailwind colour names: short, role-first, so markup reads `bg-surface text-secondary border-line`. */
const tailwindColorName = (path) => {
  const [group, key, sub] = path;
  switch (group) {
    case 'bg':
      return kebab(key);
    case 'text':
      return kebab(key);
    case 'border':
      return key === 'default' ? 'line' : `line-${kebab(key)}`;
    case 'accent':
      if (key === 'default') return 'accent';
      if (key === 'onSubtle') return 'on-accent-subtle';
      if (key === 'glow') return 'glow';
      return `accent-${kebab(key)}`;
    case 'focus':
      return 'focus';
    case 'destructive':
      if (key === 'default') return 'danger';
      if (key === 'onDefault') return 'on-danger';
      return `danger-${kebab(key)}`;
    case 'status': {
      const name = key === 'danger' ? 'error' : key;
      return sub === 'fg' ? name : `${name}-${sub}`;
    }
    case 'map':
      return kebab(key);
    case 'overlay':
      return kebab(key);
    default:
      throw new Error(`No Tailwind name for colour ${path.join('.')}`);
  }
};

const cssShadow = (layers) =>
  layers.map((l) => `${l.x}px ${l.y}px ${l.blur}px ${l.spread}px ${l.color}`).join(', ');

const cssEasing = ([a, b, c, d]) => `cubic-bezier(${a}, ${b}, ${c}, ${d})`;

const FONT_STACK = {
  // Web self-hosts the variable fonts via @fontsource-variable, which names them "… Variable".
  sans: `'${tokens.typography.family.sans} Variable', '${tokens.typography.family.sans}', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`,
  mono: `'${tokens.typography.family.mono} Variable', '${tokens.typography.family.mono}', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace`,
};

const dartColor = (hex) => {
  const h = hex.replace('#', '').toUpperCase();
  const rgb = h.slice(0, 6);
  const alpha = h.length === 8 ? h.slice(6, 8) : 'FF';
  return `Color(0x${alpha}${rgb})`;
};

const dartNum = (n) => (Number.isInteger(n) ? `${n}` : `${+n.toFixed(4)}`);

// ---------- CSS ----------

function buildCss() {
  const lightColors = flatten(tokens.color.light);
  const darkColors = flatten(tokens.color.dark);
  const colorBlock = (entries) => entries.map(([p, v]) => `  ${cssVar(p)}: ${v};`).join('\n');
  const shadowBlock = (theme) =>
    Object.entries(tokens.elevation[theme])
      .map(([k, layers]) => `  --fp-shadow-${k}: ${cssShadow(layers)};`)
      .join('\n');

  const darkBody = [`  color-scheme: dark;`, colorBlock(darkColors), shadowBlock('dark')].join('\n');

  const staticVars = [
    ...Object.entries(tokens.space).map(([k, v]) => `  --fp-space-${k}: ${v}px;`),
    ...Object.entries(tokens.radius).map(([k, v]) => `  --fp-radius-${kebab(k)}: ${v}px;`),
    ...Object.entries(tokens.size).map(([k, v]) => `  --fp-size-${kebab(k)}: ${v}px;`),
    ...Object.entries(tokens.motion.duration).map(([k, v]) => `  --fp-duration-${kebab(k)}: ${v}ms;`),
    ...Object.entries(tokens.motion.easing).map(([k, v]) => `  --fp-ease-${kebab(k)}: ${cssEasing(v)};`),
    ...Object.entries(tokens.z).map(([k, v]) => `  --fp-z-${kebab(k)}: ${v};`),
    `  --fp-font-sans: ${FONT_STACK.sans};`,
    `  --fp-font-mono: ${FONT_STACK.mono};`,
  ].join('\n');

  // Clearing each namespace with `initial` removes Tailwind's default palette, radii, shadows and
  // type sizes, so only design-system values can be used in markup.
  const theme = [
    '  --color-*: initial;',
    ...lightColors.map(([p]) => `  --color-${tailwindColorName(p)}: var(${cssVar(p)});`),
    '',
    '  --radius-*: initial;',
    ...Object.keys(tokens.radius).map((k) => `  --radius-${kebab(k)}: var(--fp-radius-${kebab(k)});`),
    '',
    '  --shadow-*: initial;',
    ...Object.keys(tokens.elevation.light).map((k) => `  --shadow-${k}: var(--fp-shadow-${k});`),
    '',
    '  --font-*: initial;',
    '  --font-sans: var(--fp-font-sans);',
    '  --font-mono: var(--fp-font-mono);',
    '',
    '  --text-*: initial;',
    ...Object.entries(tokens.typography.scale).flatMap(([k, s]) => {
      const name = `--text-${kebab(k)}`;
      return [
        `  ${name}: ${s.size}px;`,
        `  ${name}--line-height: ${s.lineHeight}px;`,
        `  ${name}--font-weight: ${s.weight};`,
        `  ${name}--letter-spacing: ${s.tracking}em;`,
      ];
    }),
    '',
    '  --ease-*: initial;',
    ...Object.keys(tokens.motion.easing).map((k) => `  --ease-${kebab(k)}: var(--fp-ease-${kebab(k)});`),
    '',
    '  --breakpoint-*: initial;',
    ...Object.entries(tokens.breakpoint).map(([k, v]) => `  --breakpoint-${k}: ${v}px;`),
  ].join('\n');

  return `/* ${HEADER} */

:root {
  color-scheme: light;
${colorBlock(lightColors)}
${shadowBlock('light')}
${staticVars}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${darkBody.replace(/^/gm, '  ')}
  }
}

:root[data-theme='dark'] {
${darkBody}
}

@theme inline {
${theme}
}
`;
}

// ---------- Dart ----------

function buildDart() {
  const lightColors = flatten(tokens.color.light);
  const darkMap = new Map(flatten(tokens.color.dark).map(([p, v]) => [p.join('.'), v]));
  const names = lightColors.map(([p]) => camel(p));

  const colorsClass = `
/// Colour roles. Read with \`Theme.of(context).extension<FpColors>()!\` (see app_theme.dart).
@immutable
class FpColors extends ThemeExtension<FpColors> {
  const FpColors({
${names.map((n) => `    required this.${n},`).join('\n')}
  });

${names.map((n) => `  final Color ${n};`).join('\n')}

  @override
  FpColors copyWith({
${names.map((n) => `    Color? ${n},`).join('\n')}
  }) {
    return FpColors(
${names.map((n) => `      ${n}: ${n} ?? this.${n},`).join('\n')}
    );
  }

  @override
  FpColors lerp(covariant FpColors? other, double t) {
    if (other == null) return this;
    return FpColors(
${names.map((n) => `      ${n}: Color.lerp(${n}, other.${n}, t)!,`).join('\n')}
    );
  }
}

const fpLightColors = FpColors(
${lightColors.map(([p, v]) => `  ${camel(p)}: ${dartColor(v)},`).join('\n')}
);

const fpDarkColors = FpColors(
${lightColors.map(([p]) => `  ${camel(p)}: ${dartColor(darkMap.get(p.join('.')))},`).join('\n')}
);
`;

  const shadowKeys = Object.keys(tokens.elevation.light);
  const shadowList = (layers) =>
    `[\n${layers
      .map(
        (l) =>
          `    BoxShadow(offset: Offset(${l.x}, ${l.y}), blurRadius: ${l.blur}, spreadRadius: ${l.spread}, color: ${dartColor(l.color)}),`,
      )
      .join('\n')}\n  ]`;

  const shadowsClass = `
/// Elevation. Dark theme leans on surface steps + borders; shadows are a secondary cue.
@immutable
class FpShadows extends ThemeExtension<FpShadows> {
  const FpShadows({${shadowKeys.map((k) => `required this.${k}`).join(', ')}});

${shadowKeys.map((k) => `  final List<BoxShadow> ${k};`).join('\n')}

  @override
  FpShadows copyWith({${shadowKeys.map((k) => `List<BoxShadow>? ${k}`).join(', ')}}) {
    return FpShadows(${shadowKeys.map((k) => `${k}: ${k} ?? this.${k}`).join(', ')});
  }

  @override
  FpShadows lerp(covariant FpShadows? other, double t) {
    if (other == null) return this;
    return FpShadows(
${shadowKeys.map((k) => `      ${k}: BoxShadow.lerpList(${k}, other.${k}, t)!,`).join('\n')}
    );
  }
}

const fpLightShadows = FpShadows(
${shadowKeys.map((k) => `  ${k}: ${shadowList(tokens.elevation.light[k])},`).join('\n')}
);

const fpDarkShadows = FpShadows(
${shadowKeys.map((k) => `  ${k}: ${shadowList(tokens.elevation.dark[k])},`).join('\n')}
);
`;

  const space = Object.entries(tokens.space)
    .map(([k, v]) => `  static const double s${k} = ${v};`)
    .join('\n');

  const radius = Object.entries(tokens.radius)
    .map(([k, v]) => `  static const double ${k} = ${v};`)
    .join('\n');
  const corners = Object.entries(tokens.radius)
    .filter(([k]) => k !== 'none')
    .map(([k, v]) => `  static const BorderRadius ${k} = BorderRadius.all(Radius.circular(${v}));`)
    .join('\n');

  const size = Object.entries(tokens.size)
    .map(([k, v]) => `  static const double ${k} = ${v};`)
    .join('\n');

  const breakpoints = Object.entries(tokens.breakpoint)
    .map(([k, v]) => `  static const double ${k} = ${v};`)
    .join('\n');

  const durations = Object.entries(tokens.motion.duration)
    .map(([k, v]) => `  static const Duration ${k} = Duration(milliseconds: ${v});`)
    .join('\n');
  const easings = Object.entries(tokens.motion.easing)
    .map(([k, [a, b, c, d]]) => `  static const Cubic ${k} = Cubic(${a}, ${b}, ${c}, ${d});`)
    .join('\n');

  const families = tokens.typography.family;
  const text = Object.entries(tokens.typography.scale)
    .map(([k, s]) => {
      const tracking = dartNum(s.tracking * s.size);
      return `  static const TextStyle ${k} = TextStyle(
    fontFamily: '${families[s.family]}',
    fontSize: ${s.size},
    height: ${s.lineHeight} / ${s.size},
    fontWeight: FontWeight.w${s.weight},
    // Bundled fonts are variable; drive the wght axis explicitly.
    fontVariations: <FontVariation>[FontVariation('wght', ${s.weight})],
    letterSpacing: ${tracking},
    leadingDistribution: TextLeadingDistribution.even,
  );`;
    })
    .join('\n\n');

  return `// ${HEADER}
// dart format off
// ignore_for_file: prefer_int_literals

import 'package:flutter/material.dart';
${colorsClass}${shadowsClass}
/// 4 px grid. \`FpSpace.s4\` = 16.
abstract final class FpSpace {
${space}
}

abstract final class FpRadius {
${radius}
}

abstract final class FpCorners {
${corners}
}

abstract final class FpSize {
${size}
}

abstract final class FpBreakpoint {
${breakpoints}
}

abstract final class FpMotion {
${durations}

${easings}
}

/// Type scale. Colour is applied by the theme, never baked in here.
abstract final class FpText {
${text}
}
`;
}

// ---------- countries (Dart) ----------
// Web imports shared/countries.json directly; Flutter can't read files outside its package at
// runtime, so it gets a const table.

function buildCountriesDart() {
  const data = read('shared/countries.json');
  const str = (s) => (s === null ? 'null' : `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`);
  const raw = (s) => `r'${s}'`;
  const rows = data.countries
    .map(
      (c) => `  FpCountry(
    iso: ${str(c.iso)},
    name: ${str(c.name)},
    dialCode: ${str(c.dialCode)},
    trunkPrefix: ${str(c.trunkPrefix)},
    minLength: ${c.nationalLength[0]},
    maxLength: ${c.nationalLength[1]},
    mobilePattern: ${raw(c.mobilePattern)},
    groups: [${c.groups.join(', ')}],
    example: ${str(c.example)},
  ),`,
    )
    .join('\n');

  return `// GENERATED by scripts/gen-shared.mjs from shared/countries.json. Do not edit by hand.
// dart format off

class FpCountry {
  const FpCountry({
    required this.iso,
    required this.name,
    required this.dialCode,
    required this.trunkPrefix,
    required this.minLength,
    required this.maxLength,
    required this.mobilePattern,
    required this.groups,
    required this.example,
  });

  final String iso;
  final String name;
  final String dialCode;
  final String? trunkPrefix;
  final int minLength;
  final int maxLength;
  final String mobilePattern;
  final List<int> groups;
  final String example;
}

const String kDefaultCountryIso = ${str(data.defaultCountry)};

const List<FpCountry> kCountries = [
${rows}
];
`;
}

// ---------- write / check ----------

const outputs = [
  ['web/src/design-system/tokens.css', buildCss()],
  ['mobile/lib/core/generated/tokens.g.dart', buildDart()],
  ['mobile/lib/core/generated/countries.g.dart', buildCountriesDart()],
];

const check = process.argv.includes('--check');
let stale = 0;

for (const [path, content] of outputs) {
  const abs = root + path;
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (check) {
    if (current !== content) {
      console.error(`Stale: ${path}. Run \`npm run gen\`.`);
      stale++;
    }
    continue;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  console.log(`wrote ${relative(root, abs)}`);
}

if (check) {
  console.log(stale ? `${stale} generated file(s) stale.` : 'Generated files are up to date.');
  process.exit(stale ? 1 : 0);
}
